[browser]
gatherUsageStats = false

[server]
headless = false
address = "localhost"
port = 8501
fileWatcherType = "auto"
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#10b981"
backgroundColor = "#080e1a"
secondaryBackgroundColor = "#0f172a"
textColor = "#ffffff"
font = "sans serif"
